### ISSUE TITLE
What should the prefix be?

### ISSUE THREAD

**Issue by castastrophe** [castastrophe/wc-theming-standards#2]
I initially proposed the `--wc-theme` prefix to all the theme variables but I'm wondering if that's even more specific than we need to be?  These theming variables can be used in vanilla HTML as well as web components to create consistency so maybe `--theme` is sufficient?

**Comment by heyMP** [comment]
Yeah definitely. I would lean more toward the `--theme` prefix since this could be a standard for all component based projects even if they aren't WC.

**Comment by starryeyez024** [comment]
I'd second what @heyMP said :)

**Comment by jouni** [comment]
If a prefix is needed, I also agree that `--theme` is enough.

Wondering if there’s a need for a prefix, though. I think these properties are defined at the top level, so any overrides happen seamlessly and as expected in the cascade.

If a website/app has decided to use a property with an exact same name (e.g. `--font-family--heading`), I think it would be fair to assume they would want that to apply to the ”themed” components as well, and not have to define the same property again e.g. `--theme-font-family--headering: var(--font-family--heading)`.

One caveat with not having a prefix is if a website/app uses the same property name but with a value that is unexpected, which ends up breaking the component rendering somehow. For example, using something like `--spacing--internal:true;` which is used from JS, and a themed component would expect that to be a padding value like `24px`.

**Comment by btopro** [comment]
@jouni goal would be to avoid that last one. 3 different projects leverage component vars, opening almost wildcard-esk support for who ever happens to supply the "theme" layer. In RH's case that might be Angular or a Drupal site, in our case a Drupal, static HTML, or PWA/SPA app. The components throughout have no idea what is supplying the "theme" layer and if we'd agree to a prefix naming convention I'd be able to safely mix Patternfly's elements into the lrnwebcomponents (and visa versa) we've created and they'd have a common css var language of theme vs local element overrides.

This proposal makes the most sense when considering a `--our-custom-button--FontSize` css var would trump the `--theme--FontSize` var that a different app supplies.

**Comment by btopro** [comment]
also agreeing w/ @heyMP sentiment that then it's not specific to WCs which could help some others into the boat who might go "ugh i dont use those" :)

**Comment by castastrophe** [comment]
It's seemingly like we have some consensus on this that `--theme` is sufficient so I'll close this issue and update the doc.  Feel free to keep conversing here or reopen this if there is more to discuss though!
