### ISSUE TITLE
Sprinkle in some _ underscores _ ?

### ISSUE THREAD

**Issue by wesruv** [castastrophe/wc-theming-standards#5]
I really like the thoughts going into this, I wonder if some underscores could add value, similar to how BEM uses `--` and `__` to denote different things?

I'd keep it consistent with BEM if this seems like it could be helpful, having `--` denote an adjective, e.g.  `lg`, `highlighted`, etc.

Still wrapping my head around this, so I'm not sure if this would add value or not.

**Comment by castastrophe** [comment]
Definitely open to suggestions!  I did use BEM naming for the proposed variables but as there were no specific regions being defined, I didn't see a use-case for underscores.  Did you see a good place to use them to add clarity?

**Comment by wesruv** [comment]
I'm not sure that this thought holds water, but I'll try writing it down and take it for what it is(n't) worth.

Putting on my picky design principles nerd hat, I think `--` create more visual noise than `__`. Seeing so many `--` makes my eyeballs a little grumpy.

What if `--` was only used for adjectives, style properties, and for the prefix of something to say it's a var?

So (stealing somewhat sloppily from the proposed vars page) this:

```
--theme--color--ui--link
--theme--color--ui--link--TextDecoration
--theme--color--ui--link--on-dark
--theme--color--ui--link--on-dark--visited
--theme--color--ui--base
--theme--color--ui--base--text
--theme--color--ui--base--text--hover
--theme--ui--BorderWidth
--theme--ui--BorderRadius
--theme--ui--BorderColor
--theme--color--surface
--theme--surface--BorderWidth
--theme--surface--BorderRadius
--theme--spacing--container
--theme--spacing--padding
--theme--spacing--content
--theme--FontSize
--theme--FontSize--alpha
--theme--LineHeight
--theme--LineHeight
--theme--LineHeight--alpha
--theme--FontWeight
--theme--FontWeight
--theme--FontWeight--alpha
--theme--FontFamily
--theme--FontFamily--heading
--theme--animation-timing
--theme--shadow
--theme--shadow--inset
```

Became this instead:
```
--theme__color__ui__link
--theme__color__ui__link__TextDecoration
--theme__color__ui__link--on-dark
--theme__color__ui__link--on-dark--visited
--theme__color__ui__base
--theme__color__ui__base__text
--theme__color__ui__base__text--hover
--theme__ui__BorderWidth
--theme__ui__BorderRadius
--theme__ui__BorderColor
--theme__color__surface
--theme__surface__BorderWidth
--theme__surface__BorderRadius
--theme__spacing__container
--theme__spacing__padding
--theme__spacing__content
--theme__FontSize
--theme__FontSize--alpha
--theme__LineHeight
--theme__LineHeight
--theme__LineHeight--alpha
--theme__FontWeight
--theme__FontWeight--alpha
--theme__FontFamily
--theme__FontFamily--heading
--theme__animation-timing
--theme__shadow
--theme__shadow--inset
```

I find the latter to be less unattractive? and maybe it adds some value?

**Comment by castastrophe** [comment]
I think we're going to use BEM for now since there seems to be some consensus around this format in the industry.
