### ISSUE TITLE
Color naming convention

### ISSUE THREAD

**Issue by wesruv** [castastrophe/wc-theming-standards#6]
A color naming convention we used at my last job that I really liked was describing the "hue" (what part of the rainbow) and then describing the value (lightness or darkness).

So some examples might be:
```
grayscale-0 // Black
grayscale-10
grayscale-100 // White

blue-10
blue-20
blue-50
blue-55 // We ended up adding a color midway through the project
blue-60

red-10
red-60

yellow-70
yellow-90
```

The idea wasn't that the value would be exact, but an approximation so you'd have an idea of what you was available/what you were getting.

This might not be too valuable in a system that's trying to abstract, but could be an implementation example. I've always found I have two sets of color variables in my projects, color by function (link color, button color, site background) and color by description (like above).

Sometimes I want something to be blue because it should be blue, sometimes I want something to be blue because it matches the link color, so I'd use one or the other variable.

**Comment by jouni** [comment]
The color palette concepts introduced by Material Design have a similar approach, where each color has a number: 50, 100, 200, ..., 800, 900. 

It’s similar how font weights are defined in CSS (100=extralight, 200=light, 300=thin, 400=regular, 500=medium, 600=semibold, 700=bold, 800=extrabold, 900=black). Not sure if the numbering system is used in other typography contexts.

Having “weights” for colors resonates with me at least.

**Comment by castastrophe** [comment]
I'm not sure a theme needs to specific set of color variables.  I'm of the thought that storing colors as CSS variables is a bit unnecessary - those are better stored as Sass variables or in design tokens.  What is beneficial as a CSS variable is mapping those Sass color-specific variables to generically or semantically named ones.  The theme is designed to apply that palette across the components to create a unified appearance.  So if the primary brand color is blue, then we would map:

```
:root {
    --theme--color--primary: $blue-50;
}
```

And then the `---theme--color--primary` variable could be used in components such as for the accordion active state color or the button background color as a means of splashing the primary brand across the site.  If my site's primary color is red, then I would map the red Sass variable to the same `--theme--color--primary` variable.

**Comment by btopro** [comment]
similar to @castastrophe - @nikkimk used numbers 1-12 for our simple-color variables as sass variables (https://github.com/elmsln/lrnwebcomponents/blob/master/elements/simple-colors/src/simple-colors.scss) but then mapped them to corresponding css vars like `--simple-colors-default-theme-light-blue-7`. Internal to an app using that then we take the primary, secondary, background, text as far as local named vars that reference the css vars.

I didn't get the need for the 100,200,300 when we're trying to build a specific color pallet to make sure people aren't generating things like 126 (or whatever) as a custom hue of light-blue. its 6,7 or 8 (etc).
